apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: trillian
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: trillian
    app.kubernetes.io/part-of: trillian
  name: trillian
spec:
  ports:
  - port: 3306
    targetPort: 3306
  selector:
    app.kubernetes.io/instance: trillian
status:
  loadBalancer: {}
